### ISSUE TITLE
Add support for html and php files

### ISSUE THREAD

**Issue by nickasd** [karl-sjogren/brackets-handlebars-templates#7]
Hi, this plugin sounds great. Unfortunately I'm used to including the Handlebars templates inside the HTML/PHP files and there is no syntax highlighting for those. Do you think it would be possible to add support for them? I have some basic experience with CodeMirror so I could try to do it myself if you think it would be a good addition.

**Comment by karl-sjogren** [comment]
I have no idea to be honest, I haven't launched Brackets for at least a year or maybe longer so this plugin is kinda dead in the water now (as is the plugin I forked this from). You could look into https://github.com/apezel/brackets-ember-htmlbars which was forked from this project or create your own fork from either project.

**Comment by nickasd** [comment]
Thanks, I will have a look.
